title: Mikael Torndahl - Blog
author: micketorndahl
email: micketorndahl@hotmail.com
description: The journey to become a full stack web developer.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
